// Generated by gencpp from file gbh_test/test.msg
// DO NOT EDIT!


#ifndef GBH_TEST_MESSAGE_TEST_H
#define GBH_TEST_MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gbh_test
{
template <class ContainerAllocator>
struct test_
{
  typedef test_<ContainerAllocator> Type;

  test_()
    : CameraReady(0)
    , bool_detection(0)
    , angle(0.0)  {
    }
  test_(const ContainerAllocator& _alloc)
    : CameraReady(0)
    , bool_detection(0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _CameraReady_type;
  _CameraReady_type CameraReady;

   typedef uint32_t _bool_detection_type;
  _bool_detection_type bool_detection;

   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::gbh_test::test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gbh_test::test_<ContainerAllocator> const> ConstPtr;

}; // struct test_

typedef ::gbh_test::test_<std::allocator<void> > test;

typedef boost::shared_ptr< ::gbh_test::test > testPtr;
typedef boost::shared_ptr< ::gbh_test::test const> testConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gbh_test::test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gbh_test::test_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gbh_test::test_<ContainerAllocator1> & lhs, const ::gbh_test::test_<ContainerAllocator2> & rhs)
{
  return lhs.CameraReady == rhs.CameraReady &&
    lhs.bool_detection == rhs.bool_detection &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gbh_test::test_<ContainerAllocator1> & lhs, const ::gbh_test::test_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gbh_test

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gbh_test::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gbh_test::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gbh_test::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gbh_test::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gbh_test::test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gbh_test::test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gbh_test::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f641958e6cc2e90ce9803fca42afaf8b";
  }

  static const char* value(const ::gbh_test::test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf641958e6cc2e90cULL;
  static const uint64_t static_value2 = 0xe9803fca42afaf8bULL;
};

template<class ContainerAllocator>
struct DataType< ::gbh_test::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gbh_test/test";
  }

  static const char* value(const ::gbh_test::test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gbh_test::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 CameraReady\n"
"uint32 bool_detection\n"
"\n"
"float32 angle\n"
"\n"
;
  }

  static const char* value(const ::gbh_test::test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gbh_test::test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.CameraReady);
      stream.next(m.bool_detection);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gbh_test::test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gbh_test::test_<ContainerAllocator>& v)
  {
    s << indent << "CameraReady: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.CameraReady);
    s << indent << "bool_detection: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bool_detection);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GBH_TEST_MESSAGE_TEST_H
